### ISSUE TITLE
webapi installation problems

### ISSUE THREAD

**Issue by nittti** [fginter/dep_search#10]
Failed to install web api.

The `index.html` in master does not render visualizations and simply opens CONLL-U output. I've tried `index.html` from http://bionlp-www.utu.fi/dep_search/, but even after changing form input names (e.g. `treeset`->`db`) it doesn't work because it seems to expect .json and not .conllu from the server. I am trying to install locally to search in not-yet-released UD shared task data and in development versions before pushing to UD.

**Comment by mjluot** [comment]
Hello and thanks for your interest!

I'm not sure of the problem based on your description. Just tested installing a local webgui and was successful. So, I guess I'll list all my commands and actions and hope it will help. If it doesn't please tell!

1. Build

git clone https://github.com/fginter/dep_search.git
cd dep_search/
git submodule init
git submodule update
make

2. Index

cat ../../depsearch_comb/test_bench/test_bank/fi-ud-train.conllu | python build_index.py -d ./fin_ud/

3. Start API process

cd webapi/

*modified corpora.yaml into:
PBV4:
  paths: /home/mjluot/Projects/vanilla_ds/dep_search/fin_ud/
  name: Fin_ud

python serve_webapi.py

4. Build and start local webgui

git clone https://github.com/fginter/dep_search_serve.git
cd dep_search_serve
echo DEP_SEARCH_WEBAPI=\"http://localhost:45678\" > config_local.py
python serve_depsearch.py

5. Use the gui

chromium-browser http://localhost:5000

Also, have a look at https://fginter.github.io/dep_search/webui.html

**Comment by nittti** [comment]
Oh, thank you!
The reason I had problems is that I didn't know [dep_search_serve](https://github.com/fginter/dep_search_serve.git) repo existed and tried /webapi from this very repo. Your instructions did work! (I also had to update `corpus_groups.yaml`).
Thanks!
