### ISSUE TITLE
how to cite?

### ISSUE THREAD

**Issue by arademaker** [fginter/dep_search#9]
any article about this project? How to cite it ?

**Comment by fginter** [comment]
Thanks for asking. :)

@inproceedings{luotolahti2015sets, author = {Juhani Luotolahti and Jenna Kanerva and Sampo Pyysalo and Filip Ginter}, title = {SETS: Scalable and Efficient Tree Search in Dependency Graphs}, booktitle = {Proceedings of the 2015 Conference of the North American Chapter of the Association for Computational Linguistics: Demonstrations}, publisher = {Association for Computational Linguistics}, year = {2015}, pages = {51--55}, url = {https://aclweb.org/anthology/N/N15/N15-3011.pdf} }
